services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - db_data:/data
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    
  
#  frontend:
#    build:
#      context: ./frontend
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend

volumes:
  db_data: